name: Deploy to Staging

on:
  push:
    branches: [main]

jobs:
  deploy-firebase-rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Firestore & Storage rules
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only firestore:rules,storage
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
